project:
  type: website
  preview: 
    port: 4200
    browser: true

website:
  title: "Samantha Seals, PhD"
  description: ""
  site-url: "https://samanthaseals.github.io"
  search: false
  navbar:
    background: "#f8d6e0"    # pastel pink
    foreground: "#4b3f72"    # deep muted purple for contrast
    left:
      - text: "Research"
        href: pages/research.qmd
      - text: "Teaching"
        href: pages/teaching.qmd
    right:
      - icon: github
        href: "https://github.com/samanthaseals"

format:
  html:
    theme:
      light: [flatly, styles.scss]
    mainfont: "Lato"
    monofont: "Fira Code"
    toc: false
    toc-depth: 3
    page-layout: full
    linkcolor: "#a68ac4"   # lavender link color
    fontsize: 1.05em