permalink: /:categories/:title/
baseurl: ""  # Keep this empty for user sites like samanthaseals.github.io

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false