permalink: /:categories/:title/
baseurl: ""  # Keep this empty for user sites like samanthaseals.github.io

include: _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      permalink: /:basename/
      layout: single      
      

  
  
